name = "VHSJuliaKursPackage"
uuid = "672059b2-b5a9-4b92-854d-f673ad28ae36"
authors = ["Frank Zimmer <frank.e.zimmer@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]


[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["Test","TestItems"]
